version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm lint
      - run: npm test